; G1R - Streaming Stutter Fix
; Preset: 6 GB VRAM / 3072 MB pool

[TextureQuality@0]
r.Streaming.LimitPoolSizeToVRAM=0
r.Streaming.PoolSize=3072

[TextureQuality@1]
r.Streaming.LimitPoolSizeToVRAM=0
r.Streaming.PoolSize=3072

[TextureQuality@2]
r.Streaming.LimitPoolSizeToVRAM=0
r.Streaming.PoolSize=3072

[TextureQuality@3]
r.Streaming.LimitPoolSizeToVRAM=0
r.Streaming.PoolSize=3072

[TextureQuality@Cine]
r.Streaming.LimitPoolSizeToVRAM=0
r.Streaming.PoolSize=3072
