; G1R - Streaming Stutter Fix
; Preset: 24+ GB VRAM / 12288 MB pool

[TextureQuality@0]
r.Streaming.LimitPoolSizeToVRAM=0
r.Streaming.PoolSize=12288

[TextureQuality@1]
r.Streaming.LimitPoolSizeToVRAM=0
r.Streaming.PoolSize=12288

[TextureQuality@2]
r.Streaming.LimitPoolSizeToVRAM=0
r.Streaming.PoolSize=12288

[TextureQuality@3]
r.Streaming.LimitPoolSizeToVRAM=0
r.Streaming.PoolSize=12288

[TextureQuality@Cine]
r.Streaming.LimitPoolSizeToVRAM=0
r.Streaming.PoolSize=12288
