; G1R - Streaming Stutter Fix
; Preset: 8 GB VRAM / 4096 MB pool

[TextureQuality@0]
r.Streaming.LimitPoolSizeToVRAM=0
r.Streaming.PoolSize=4096

[TextureQuality@1]
r.Streaming.LimitPoolSizeToVRAM=0
r.Streaming.PoolSize=4096

[TextureQuality@2]
r.Streaming.LimitPoolSizeToVRAM=0
r.Streaming.PoolSize=4096

[TextureQuality@3]
r.Streaming.LimitPoolSizeToVRAM=0
r.Streaming.PoolSize=4096

[TextureQuality@Cine]
r.Streaming.LimitPoolSizeToVRAM=0
r.Streaming.PoolSize=4096
