; G1R - Streaming Stutter Fix
; Preset: 20 GB VRAM / 10240 MB pool

[SystemSettings]
r.TextureStreaming=1
r.Streaming.LimitPoolSizeToVRAM=0
r.Streaming.PoolSize=10240
r.Streaming.MaxTempMemoryAllowed=512
r.Streaming.DefragDynamicBounds=1
r.MotionBlurQuality=0
r.ShaderPipelineCache.Enabled=1
r.ShaderPipelineCache.StartupMode=2
r.ShaderPipelineCache.BatchSize=64
r.ShaderPipelineCache.BackgroundBatchSize=8
r.ShaderPipelineCache.BatchTime=2
r.ShaderPipelineCache.BackgroundBatchTime=1
s.AsyncLoadingTimeLimit=5
s.PriorityAsyncLoadingExtraTime=15
s.LevelStreamingActorsUpdateTimeLimit=5
s.PriorityLevelStreamingActorsUpdateExtraTime=15
