; G1R - Streaming Stutter Fix
; Preset: 20 GB VRAM / 10240 MB pool

[TextureQuality@0]
r.Streaming.LimitPoolSizeToVRAM=0
r.Streaming.PoolSize=10240

[TextureQuality@1]
r.Streaming.LimitPoolSizeToVRAM=0
r.Streaming.PoolSize=10240

[TextureQuality@2]
r.Streaming.LimitPoolSizeToVRAM=0
r.Streaming.PoolSize=10240

[TextureQuality@3]
r.Streaming.LimitPoolSizeToVRAM=0
r.Streaming.PoolSize=10240

[TextureQuality@Cine]
r.Streaming.LimitPoolSizeToVRAM=0
r.Streaming.PoolSize=10240
