; G1R - Streaming Stutter Fix
; Preset: 4 GB VRAM / 1536 MB pool

[TextureQuality@0]
r.Streaming.LimitPoolSizeToVRAM=0
r.Streaming.PoolSize=1536

[TextureQuality@1]
r.Streaming.LimitPoolSizeToVRAM=0
r.Streaming.PoolSize=1536

[TextureQuality@2]
r.Streaming.LimitPoolSizeToVRAM=0
r.Streaming.PoolSize=1536

[TextureQuality@3]
r.Streaming.LimitPoolSizeToVRAM=0
r.Streaming.PoolSize=1536

[TextureQuality@Cine]
r.Streaming.LimitPoolSizeToVRAM=0
r.Streaming.PoolSize=1536
